version: '3.6'
services:
  reservation:
    build:
      context: .
    user: '${UID:-1000}:${GID:-1000}'
    depends_on:
      - postgres
      - redis
    command: npm run start:dev
    env_file:
      - .env.docker
    ports:
      - 3000:3003
    volumes:
      - ${PWD}/seeders:/usr/src/app/seeders
    networks:
      - reservation
  redis:
    image: bitnami/redis:4.0.12-debian-9-r11
    container_name: redisReservation
#    volumes:
#      - redis:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - reservation

  postgres:
    image: kartoza/postgis
    container_name: postgresReservation
    ports:
      - 5435:5432
    networks:
      - reservation
    environment:
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis
      - POSTGRES_USER=postgres2
      - POSTGRES_PASS=postgres2
      - POSTGRES_DBNAME=postgres2
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  reservation:
    external: true
